# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2d5e1ee9ead99833b574c56908f6e872882cc2d8d87efb5e192883fd6af8b4084cebe52922e09a14b13ccd56c3c66f36ff2d9c466088dfa51192bac3feb93768

test:
  secret_key_base: df5b8bce1754fda443578620798458dd37a55a215333f6742d883bd5ae61a19c00353d69400da6a98ca8fa352144b5102ab64729896d3b8b32dc7a44756ace92

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
